language: node_js

node_js:
  - "8"

before_script:
  - npm install -g reveal-md

script:
  - reveal-md slides/ --static build
  - cp -r slides/css build/
  - cp -r slides/js build/
  - cp -r slides/images build/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local-dir: build